### ISSUE TITLE
Unable to autoload constant Engine

### ISSUE THREAD

**Issue by duboff** [nsarno/knock#5] opened 2015-08-24 10:55 UTC
Getting the following error (I followed the Auth0 manual) 
```
LoadError (Unable to autoload constant Engine, expected /Users/mikhaildubov/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/knock-1.3.0/lib/knock/engine.rb to define it):
```

Any idea why this is happening? Appreciate any pointers.

**Comment by nsarno** [comment] 2015-08-25 07:44
I need more informations in order to help you. At least a complete stack trace. And maybe the code related to knock you added to your project. Thanks.

**Comment by duboff** [comment] 2015-08-25 08:47
Yep, so I eventually figured out it was driven by the jsonapi_resources gem. Somehow the two do not communicate correctly. I unfortunately don't have the stack trace anymore, but the problem was in this line: https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/link_builder.rb#L19

I eventually reverted to the jwt gem and it's all working now. It's a shame because knock seemed a lot cleaner.

**Comment by nsarno** [comment] 2015-08-25 09:20
If you give me more details on how to reproduce this issue, I'll be able to figure out if it comes from `knock` or `jsonapi-resources` and fix it. Thanks for your feedback.

**Comment by duboff** [comment] 2015-08-25 09:22
I think it comes from the jsonapi_resources. I have very typical API with jsonapi_resources and the recommended knock configuration, exactly like in both manuals. I'll try to create a toy app when I have time.

**Comment by nsarno** [comment] 2015-08-25 09:26
Sounds good. Maybe you can start from [this jsonapi-resources example app](https://github.com/cerebris/peeps).

**Comment by duboff** [comment] 2015-09-17 20:07
Hi, apologies for the long wait but I was finally able to replicate the problem in a demo app. It seems that the problem is somehow related to the newer version of jsonapi_resources. Here is the app: https://github.com/duboff/peeps

**Comment by duboff** [comment] 2015-09-17 20:08
To recreate, launch and try visiting http://localhost:3000/api/contacts

**Comment by nsarno** [comment] 2015-09-18 01:13
Thank you for the demo app!

I've been trying to understand what should be fixed. And it seems to me that neither `knock` or `jsonapi-resources` is doing anything wrong.

But it makes no sense to me why the following happens:

```
irb(main):005:0> Api::Engine
LoadError: Unable to autoload constant Engine, expected /Users/arno/workspace/peeps/vendor/bundle/ruby/2.2.0/gems/knock-1.3.0/lib/knock/engine.rb to define it
[...]
```

and

```
irb(main):006:0> Engine
LoadError: Unable to autoload constant Engine, expected /Users/arno/workspace/peeps/vendor/bundle/ruby/2.2.0/gems/knock-1.3.0/lib/knock/engine.rb to define it
[...]
```

I believe something like this should happen instead:

```
irb(main):007:0> Wrong
NameError: uninitialized constant Wrong
[...]
```

The path `lib/knock/engine.rb` should NOT be expected to define a constant `Engine`.
It should only be expected to define a `Knock::Engine` constant.

```
irb(main):008:0> Knock::Engine
=> Knock::Engine
```

I feel like this is a weird behavior from rails autoloading, but maybe I just don't understand well enough how this works. I'll keep digging but any help on this is welcome.

**Comment by duboff** [comment] 2015-09-18 08:06
I think it might be related to this: https://github.com/cerebris/jsonapi-resources/pull/443 which was merged recently so maybe it will go away in the next version

**Comment by nsarno** [comment] 2015-09-20 07:51
Unfortunaltey no, this issue is unrelated.

I opened another issue here: [cerebris/jsonapi-resources/issues/450](https://github.com/cerebris/jsonapi-resources/issues/450), so I'm closing this one for the moment.

**Closed by nsarno** 2015-09-20 07:51 UTC
Labels: help wanted

**Comment by tindron** [comment] 2017-03-21 22:07
This issue exists purely within knock and can be reproduced without jsonapi-resources.  The line `config.eager_load_paths += Dir["#{config.root}/lib/**/"]` in `knock/engine.rb` should be replaced with `paths.add 'lib', eager_load: true`.

**Comment by ionutzp** [comment] 2019-01-08 16:51
@tindron how did you find this fix? i'm curious because just had the same problem and your solution worked. Thanks!
